blank_issues_enabled: false
contact_links:
    - name: Questions & Discussions
      url: https://github.com/opentutorials-org/otu.oss/discussions
      about: Please ask questions and discuss ideas here instead of opening an issue.
    - name: Documentation
      url: https://github.com/opentutorials-org/otu.oss#readme
      about: Check the documentation before opening an issue.
